---
title: "TTTech"
author: "Rafael Santos Abreu"
date: '2022-07-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gridExtra)
```

Setting up the data
```{r}
technology <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-07-19/technology.csv')

```

Data Wrangling
```{r}
DFtech <- 
  technology %>% 
  filter(category == "Energy") %>% 
  filter(year >= "2000") %>% 
  filter(iso3c == "BRA") %>%
  mutate(newlabes = str_remove(label, "Electricity from "))


DFnoh <- 
  DFtech %>% 
  filter(!variable %in% c("elec_hydro", "elecprod", "elec_cons", "electric_gen_capacity"))
  


DFn <- 
  DFtech %>% 
  filter(variable == c("elec_hydro", "elecprod"))
```

Making the Graph
```{r}
g1 <- 
  DFn %>% 
  ggplot(aes(x = year, y = value, color = newlabes))+
  geom_smooth(se=FALSE)+
  theme_minimal()+
  labs(
    title = "Different forms of Energy Production in Brazil",
    subtitle = "Hydroelectricity is the most prevalent form of energy production",
    caption = "The data comes from data.nber.org",
    x = NULL,
    y = NULL,
    color = NULL
    )

```

Making the second graph
```{r}
g2 <- 
  DFnoh %>% 
  ggplot(aes(x = year, y = value, color = newlabes))+
  geom_smooth(se=FALSE)+
  theme_minimal()+
  labs(
    title = "Different forms of Energy Production in Brazil",
    subtitle = "There is no emphasis on other forms of energy production",
    caption = "The data comes from data.nber.org",
    x = NULL,
    y = NULL,
    color = NULL
    )

```

Puttin the two graphs together
```{r}
grid.arrange(g1, g2, ncol = 2)
```

